services:
  web:
    depends_on:
      - postgres_db
      - ollama  # Add dependency on the Ollama service
    build:
      context: ./proyecto
      dockerfile: Dockerfile
    image: guria:latest
    ports:
      - "8000:8000"  # Map container port 8000 to host port 8000
    env_file:
      - proyecto/.env
    environment:
      - PORT:8000 # Example environment variable
    command: sh -c "chmod +x /app/migrate.sh && sh /app/migrate.sh && /app/entrypoint.sh"

  postgres_db:
    image: postgres
    env_file:
      - proyecto/.env
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/  # Fixed volume as a list

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"  # Expose Ollama API port
    volumes:
      - ollama_volume:/root/.ollama
    # Removed GPU-specific configurations

volumes:
  postgres_data:  # Declare the named volume for PostgreSQL
  ollama_volume:  # Declare the named volume for Ollama
